#!/usr/bin/env node
/**
 * Regenerates src/inventory.data.js from data/inventory.json.
 * A plain JS module is portable across Node, Bare and Expo; JSON import
 * attributes and filesystem reads are not.
 */

import { readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.join(path.dirname(fileURLToPath(import.meta.url)), '..');
const jsonPath = path.join(root, 'data/inventory.json');
const outPath = path.join(root, 'src/inventory.data.js');

const parsed = JSON.parse(readFileSync(jsonPath, 'utf8'));
if (!Array.isArray(parsed)) {
  throw new Error('data/inventory.json must be a JSON array');
}

const body =
  '// Generated by scripts/sync-data.mjs from data/inventory.json. Do not edit by hand.\n' +
  `export default ${JSON.stringify(parsed, null, 2)}\n`;

writeFileSync(outPath, body);
process.stdout.write(`wrote ${path.relative(root, outPath)} (${parsed.length} rows)\n`);
